<?php
    session_start();
    require_once ('../assets/tcpdf/tcpdf.php');
    class MYPDF extends TCPDF {
        public function Footer(){
            $firstname= $_SESSION['username'];
            $lastname= $_SESSION['username'];
            $this -> SetY(-15);
            $this -> SetFont('Helvetica', 'BI', 10);
            $this -> Cell(0, 10, 'Generated by: '.$firstname. ' ' .$lastname,  0, false, 'L', 0, '', 0, false, 'T', 'M');
            $this -> SetY(-15);
            $this -> SetFont('Helvetica', 'I', 10);
            $this -> Cell(0, 10, 'Page ' .$this-> getAliasNumPage(), 0, false, 'R', 0, '', 0, false, 'T', 'M');
        }
    }
    function fetch_data() {
        $table_name = $_POST['doc_type'];
		 $doc_name = $_POST['doc_name'];
        $output = '';
		$datefilter = $_POST['datefilter'];
		$string=$datefilter;
		$last_space = strrpos($string, ' ');
		$last_word = substr($string, $last_space);
		$first_chunk = substr($string, 0, $last_space - 2);
		$date_from_tmp = date('Y-m-d', strtotime($first_chunk));
		$date_to_tmp = date('Y-m-d', strtotime($last_word));

        $client = $_POST['client'];
        $service_by = $_POST['service_by'];
        $min_location = $_POST['min_location'];
        $phase= $_POST['phase'];
        $agency= $_POST['agency'];
        $extension_act = $_POST['extension_act'];
		$report_name= $_POST['report_name'];
			include ('../inc/dbc.inc.php');
			
			
			
        if ($table_name == "res_pms") {
            if ($client == "null" &&   $service_by == "null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, schedule.schedule_date, schedule.client_id, clients.client_name, clients.client_address, machine.machine_model from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine on schedule.machine_id = machine.machine_id) where schedule.contract_id !='' ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                     
                    </tr>';  
                }
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, clients.client_name, clients.client_address, machine.machine_model from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine on schedule.machine_id = machine.machine_id) where schedule.contract_id !='' and clients.client_id = '$client' and pms.service_by = '$service_by'";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, clients.client_name, clients.client_address, machine.machine_model from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine on schedule.machine_id = machine.machine_id) where schedule.contract_id !='' and clients.client_id = '$client' ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, clients.client_name, clients.client_address, machine.machine_model from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine on schedule.machine_id = machine.machine_id) where schedule.contract_id !='' and pms.service_by = '$service_by' ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
        }
        //Minutes of Meeting
        elseif ($table_name == "minutes_meeting") {
            if ($min_location != "null" && $participants == "null" )  {
                $sql = "SELECT * FROM minutes_meeting WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp'  AND `location` = '$min_location' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                   $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['location'].'</td>  
                        <td>'.$row['participants'].'</td>  
                        <td>'.$row['description'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
			}  }
            } elseif($participants !="null" && $min_location !="null") {
                $sql = "SELECT * FROM minutes_meeting WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp'  AND `participants` = '$participants' AND `location` = '$min_location' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                   $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['location'].'</td>  
                        <td>'.$row['participants'].'</td>  
                        <td>'.$row['description'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
			} }
            } elseif($participants !="null" && $min_location =="null") {
                $sql = "SELECT * FROM minutes_meeting WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp'  AND `participants` = '$participants' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                   $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['location'].'</td>  
                        <td>'.$row['participants'].'</td>  
                        <td>'.$row['description'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
			}  }
            } elseif ($participants == "null" && $min_location == "null")  {
                $sql = "SELECT * FROM minutes_meeting WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                   $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['location'].'</td>  
                        <td>'.$row['participants'].'</td>  
                        <td>'.$row['description'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
			}  }
            }
        }
        //Incoming Communication
        elseif ($table_name == "incoming_comm") {
            if ($phase != "null" && $agency == "null") {
                $sql = "SELECT * FROM incoming_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `phase` ='$phase' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) { 
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';
                }}
            } elseif ($agency !="null" && $phase !="null")  {
                $sql = "SELECT * FROM incoming_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `agency` = '$agency' AND `phase` = '$phase' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                }}
            } elseif ($agency!="null" && $phase="null")  {
                $sql = "SELECT * FROM incoming_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `agency` = '$agency' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                } }
            } elseif ($agency =="null" && $phase =="null")  {
                $sql = "SELECT * FROM incoming_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                } }
            }
        }
        //Incoming Communication
        elseif ($table_name == "outgoing_comm") {
            if ($phase != "null" && $agency == "null") {
                $sql = "SELECT * FROM outgoing_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `phase` ='$phase' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';
			}}
            } elseif ($agency !="null" && $phase !="null")  {
                $sql = "SELECT * FROM outgoing_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `agency` = '$agency' AND `phase` = '$phase' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                }}
            } elseif ($agency!="null" && $phase="null")  {
                $sql = "SELECT * FROM outgoing_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `agency` = '$agency' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                }}
            } elseif ($agency =="null" && $phase =="null")  {
                $sql = "SELECT * FROM outgoing_comm WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['id'].'</td>  
                        <td>'.$row['file_name'].'</td>  
                        <td>'.$row['agency'].'</td>  
                        <td>'.$row['purpose'].'</td>  
                        <td>'.$row['phase'].'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.$row1['date_uploaded'].'</td> 
                    </tr>';  
                }}
            }
        }
        // Proposal
        elseif ($table_name == "proposal_module") {
            $sql = "SELECT * FROM proposal_module ORDER BY id ASC";  
            $result = mysqli_query($conn, $sql);  
            while($row = mysqli_fetch_array($result)) {  
				$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `date_uploaded` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                $output .= 
                '<tr align="center">  
                    <td>'.$row['id'].'</td>  
                    <td>'.$row['file_name'].'</td>  
                    <td>'.$row['agenda'].'</td>  
                    <td>'.$row1['date_uploaded'].'</td> 
                </tr>';  
            }}
        }
        // Other
        elseif ($table_name == "other") {
            $sql = "SELECT * FROM other ORDER BY id ASC";  
            $result = mysqli_query($conn, $sql);  
            while($row = mysqli_fetch_array($result)) {  
				$fetch = $row['file_id'];
						  $sql1 = "SELECT * FROM file WHERE `date_uploaded` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `file_id` ='$fetch'";  
                    $result1 = mysqli_query($conn, $sql1);  
					while($row1 = mysqli_fetch_array($result1)) {
                $output .= 
                '<tr align="center">  
                    <td>'.$row['id'].'</td>  
                    <td>'.$row['file_name'].'</td>  
                    <td>'.$row['description'].'</td>  
                    <td>'.$row1['date_uploaded'].'</td> 
                </tr>'; 
            }}
        }
        // Extension Activity
        elseif ($table_name == "extension") {
            if ($extension_act=="null") {
                $sql = "SELECT * FROM extActivity_file WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {		
                    $fetch1= $row['extension_act']; 
                    $sql1 = "SELECT * FROM extension_activity WHERE `id` ='$fetch1' ORDER BY id ASC";  
                    $result1 = mysqli_query($conn, $sql1);  
                    while($row1 = mysqli_fetch_array($result1)) {
                        $output .= 
                            '<tr align="center">  
                                <td>'.$row['id'].'</td>  
                                <td>'.$row1['extension_act'].'</td>  
                                <td>'.$row['file_name'].'</td>  
                                <td>'.$row['description'].'</td>  
                                <td>'.$row['date'].'</td>
                            </tr>';  
                    }
                }
            } elseif ($extension_act!="null") {
                $sql = "SELECT * FROM extActivity_file WHERE `date` BETWEEN '$date_from_tmp' AND '$date_to_tmp' AND `extension_act`= '$extension_act' ORDER BY id ASC";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {			 
                    $fetch1= $row['extension_act']; 
                    $sql1 = "SELECT * FROM extension_activity WHERE `id` ='$fetch1' ORDER BY id ASC";  
                    $result1 = mysqli_query($conn, $sql1);  
                    while($row1 = mysqli_fetch_array($result1)) {	
                        $output .= 
                        '<tr align="center">  
                            <td>'.$row['id'].'</td>  
                            <td>'.$row1['extension_act'].'</td>  
                            <td>'.$row['file_name'].'</td>  
                            <td>'.$row['description'].'</td>  
                            <td>'.$row['date'].'</td>
                        </tr>';  
                    }
                }
            }
        }
        return $output;  
    }  
    if(isset($_POST["create_pdf"])) {  
        $doc_name = $_POST['doc_name'];
        $doc_type = $_POST['doc_type'];
        $date_to_tmp = $_POST['date_to'];
        $date_to = date('d F Y', strtotime($date_to_tmp));
        $date_from_tmp = $_POST['date_from'];
        $date_from = date('d F Y', strtotime($date_from_tmp));
        $table_name = $_POST['doc_type'];
        $firstname= $_SESSION['firstname'];
        $lastname= $_SESSION['lastname'];
		$report_name = $_POST['report_name']; 
        
        /// PDF
        $obj_pdf = new MYPDF('M', 'mm', 'A4'); 
        $obj_pdf->SetCreator(PDF_CREATOR);  
        $obj_pdf->SetTitle($doc_name);  
        $obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);
        
        // set header and footer fonts  
        $obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));  
        $obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA)); 
        
        // set default monospaced font
        $obj_pdf->SetDefaultMonospacedFont('helvetica');

        // set margins
        $obj_pdf->SetFooterMargin(10);
        $obj_pdf->SetMargins(PDF_MARGIN_LEFT, '11', PDF_MARGIN_RIGHT);  
        $obj_pdf->setPrintHeader(false); 
        $obj_pdf->SetAutoPageBreak(TRUE, 17);

        $obj_pdf->SetFont('helvetica', '', 12); 

        // set auto page breaks
        $obj_pdf->AddPage(); 
        $content = '';
        
        /// PDF style
        $content .= '
            <style>
                th {
                    background-color: #ccc;
                }
            </style>
            <div class="header">';
                $obj_pdf -> Image('../image/icon.jpg', 90, 10, 27);
                $obj_pdf -> SetFont('Helvetica', '', 12);
                $obj_pdf -> Cell(287, 7, "Republic of the Philippines", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', 'B', 14);
                $obj_pdf -> Cell(287, 7, "Cavite State University", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', 'B', 14);
                $obj_pdf -> Cell(287, 6, "Don Severino de las Alas Campus", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', '', 12);
                $obj_pdf -> Cell(287, 6, "Indang, Cavite", 0, 1, 'C');
                $obj_pdf -> Ln(7);
                $obj_pdf -> SetFont('Helvetica', 'B', 12);
                $obj_pdf -> Cell(277, 7, "College of Engineering and Information Technology", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', '', 12);
                $obj_pdf -> Cell(277, 7, "$doc_name", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', '', 12);
                $obj_pdf -> Cell(277, 7, "Date: $date_from - $date_to", 0, 0, 'C');
                $obj_pdf -> Ln(7);
                $obj_pdf -> SetFont('Helvetica', '', 11);
                $content .= '
            </div>
            <table border="0" cellspacing="0" cellpadding="5">';
            if ($table_name == "res_pms") {
                $content .= '
                <tr align="center">
                    <th width="20%">Client Name</th>  
                    <th width="20%">Address</th>  
                    <th width="15%">Machine</th>  
                    <th width="15%">Schedule Date</th>
                    <th width="15%">Service Date</th>
                    <th width="15%"> Service By</th>
                </tr>';
            } elseif ($table_name == "minutes_meeting") {
                $content .= '
                <tr align="center">
                    <th width="5%">ID</th>  
                    <th width="20%">File Name</th>  
                    <th width="15%">Location</th>  
                    <th width="15%">Participants</th>
                    <th width="15%">Description</th>
                    <th width="15%">Date</th>
                    <th width="15%">Uploaded Date</th>
                </tr>';
            } elseif ($table_name == "incoming_comm") {
                $content .= '
                <tr align="center">
                    <th width="5%">ID</th>  
                    <th width="20%">File Name</th>  
                    <th width="15%">Agency</th>  
                    <th width="20%">Purpose</th>
                    <th width="15%">Phase</th>
                    <th width="10%">Date</th>
                    <th width="15%">Uploaded Date</th>
                </tr>';
            } elseif ($table_name == "outgoing_comm") {
                $content .= '
                <tr align="center">
                    <th width="5%">ID</th>  
                    <th width="20%">File Name</th>  
                    <th width="15%">Agency</th>  
                    <th width="20%">Purpose</th>
                    <th width="15%">Phase</th>
                    <th width="10%">Date</th>
                    <th width="15%">Uploaded Date</th>
                </tr>';
            } elseif ($table_name == "proposal_module") {
                $content .= '
                <tr align="center">
                    <th width="10%">ID</th>  
                    <th width="30%">File Name</th>  
                    <th width="30%">Agenda</th>  
                    <th width="30%">Uploaded Date</th>
                </tr>';
            } elseif ($table_name == "other") {
                $content .= '
                <tr align="center">
                    <th width="10%">ID</th>  
                    <th width="30%">File Name</th>  
                    <th width="30%">Description</th>  
                    <th width="30%">Uploaded Date</th>
                </tr>';
            } elseif ($table_name == "extension") {
                $content .= '
                <tr align="center">
                    <th width="10%">ID</th>
				    <th width="20%">Extension Activity</th>
                    <th width="30%">File Name</th>  
                    <th width="20%">Description</th>  
                    <th width="20%">Extension Date</th>
                </tr>';
            } 
        $content .= fetch_data();  
        $content .= '</table>';  
        $obj_pdf->writeHTML($content);  
			include ('../inc/dbc.inc.php');
			$location = "../inc/files/".$report_name.'.pdf';
		$sql2= "INSERT INTO `generated_report` (`id`, `type_docu`, `location`, `date_from`, `date_to`, `report_name`, `generated_by`) VALUES (NULL, '$table_name', '$location', '$date_from_tmp','$date_to_tmp', '$report_name.pdf', '$firstname $lastname')";
		$result2 = $conn->query($sql2);
		$obj_pdf->Output(__DIR__ . '/files/'.$report_name.'.pdf', 'F');
        $obj_pdf->Output($report_name.'.pdf', 'I');
		
    }  
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Export Table Data to PDF</title>  
    <?php include '../admin/links.php'; ?>
</head>
<body>
    <section>
        <?php 
            require_once '../inc/dbc.inc.php';

            $doc_type = $_POST['doc_type'];
            $doc_name = $_POST['doc_name'];
            $date_to = $_POST['date_to'];
            $date_to_tmp = date('d F Y', strtotime($date_to));
            $date_from = $_POST['date_from'];
            $date_from_tmp = date('d F Y', strtotime($date_from));
            $doc_title = $_POST['doc_name'];
            $table_name = $_POST['doc_type'];
            $firstname= $_SESSION['firstname'];
            $lastname= $_SESSION['lastname'];
            $parties_involve= $_POST['parties_involve'];
            $participants = $_POST['participants'];
            $min_location = $_POST['min_location'];
            $phase = $_POST['phase'];
            $agency = $_POST['agency'];
            $extension_act = $_POST['extension_act'];
			$report_name= $_POST['report_name'];
        ?>
        <div class="container mt-5" style="width:1200px;">  
            <div class="header">
                <h3 class="text-center"><?php echo $doc_name; ?></h3>
                <h6 class="text-center">Date: <?php echo $date_from_tmp; ?> - <?php echo $date_to_tmp; ?></h6>
            </div>
            <br />  
            <div class="table-responsive">  
                 <table class="table table-bordered table-striped">  
                    <?php
                        if ($table_name == "memorandum_agreement") {
                            echo "<tr>  
                                <th width='5%' class='text-center'>ID</th>  
                                <th width='35%' class='text-center'>File Name</th>  
                                <th width='15%' class='text-center'>Effective Date</th>  
                                <th width='15%' class='text-center'>Parties Involve</th>  
                                <th width='15%' class='text-center'>Description</th>
                                <th width='15%' class='text-center'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "minutes_meeting") {
                            echo "
                            <tr>
                                <th class='text-center' width='5%'>ID</th>  
                                <th class='text-center' width='20%'>File Name</th>  
                                <th class='text-center' width='15%'>Location</th>  
                                <th class='text-center' width='15%'>Participants</th>
                                <th class='text-center' width='15%'>Description</th>
                                <th class='text-center' width='15%'>Date</th>
                                <th class='text-center' width='15%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "incoming_comm") {
                            echo "
                            <tr>
                                <th class='text-center' width='5%'>ID</th>  
                                <th class='text-center' width='20%'>File Name</th>  
                                <th class='text-center' width='15%'>Agency</th>  
                                <th class='text-center' width='20%'>Purpose</th>
                                <th class='text-center' width='15%'>Phase</th>
                                <th class='text-center' width='10%'>Date</th>
                                <th class='text-center' width='15%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "outgoing_comm") {
                            echo "
                            <tr>
                                <th class='text-center' width='5%'>ID</th>  
                                <th class='text-center' width='20%'>File Name</th>  
                                <th class='text-center' width='15%'>Agency</th>  
                                <th class='text-center' width='20%'>Purpose</th>
                                <th class='text-center' width='15%'>Phase</th>
                                <th class='text-center' width='10%'>Date</th>
                                <th class='text-center' width='15%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "proposal_module") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='30%'>Agenda</th>  
                                <th class='text-center' width='30%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "other") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='30%'>Description</th>  
                                <th class='text-center' width='30%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "extension") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
								<th class='text-center' width='20%'>Extension Activity</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='20%'>Description</th>  
                                <th class='text-center' width='20%'>Extension Date</th>
                            </tr>";
                        }
                    ?>
                 <?php  
                    echo fetch_data();  
                 ?> 
                 </table>
                 <h6 class="text-right">Generated by: <?php echo $firstname; echo " "; echo $lastname;?></h6>
                 <div class="form-group text-center">
                    <form method="post">
                        <input type="hidden" name="doc_type" value="<?php echo $doc_type; ?>">
                        <input type="hidden" name="doc_name" value="<?php echo $doc_name; ?>">
                        <input type="hidden" name="date_from" value="<?php echo $date_from;?>">
                        <input type="hidden" name="date_from_tmp" value="<?php echo $date_from_tmp;?>">
                        <input type="hidden" name="date_to" value="<?php echo $date_to; ?>">
                        <input type="hidden" name="date_to_tmp" value="<?php echo $date_to_tmp; ?>">
                        <input type="hidden" name="parties_involve" value="<?php echo $parties_involve; ?>">
                        <input type="hidden" name="participants" value="<?php echo $participants; ?>">
                        <input type="hidden" name="min_location" value="<?php echo $min_location; ?>">
                        <input type="hidden" name="phase" value="<?php echo $phase; ?>">
                        <input type="hidden" name="agency" value="<?php echo $agency; ?>">
                        <input type="hidden" name="extension_act" value="<?php echo $extension_act; ?>">
						  <input type="hidden" name="report_name" value="<?php echo $report_name; ?>">
						

                        <button type="submit" name="create_pdf" class="btn btn-danger">
                              <span>Create PDF</span>
                        </button> 
                    </form>
                 </div>
            </div>  
        </div>
    </section>
</body>
</html>